import type { GlossaryTerm } from "@/types/guide";

export const glossaryTerms: GlossaryTerm[] = [
  {
    id: "aws",
    term: "AWS (Amazon Web Services)",
    definition: "Nền tảng điện toán đám mây của Amazon, cung cấp hơn 200 dịch vụ từ cơ sở hạ tầng đến machine learning. AWS có mặt tại 30+ regions trên toàn thế giới.",
    category: "Core",
    relatedTerms: ["region", "availability-zone"],
  },
  {
    id: "region",
    term: "Region",
    definition: "Vùng địa lý độc lập, chứa nhiều Availability Zones (AZ). Ví dụ: ap-southeast-1 (Singapore), us-east-1 (N. Virginia). Mỗi region hoàn toàn độc lập với nhau về dữ liệu và dịch vụ.",
    category: "Core",
    relatedTerms: ["availability-zone", "global-services"],
  },
  {
    id: "availability-zone",
    term: "Availability Zone (AZ)",
    definition: "Một hoặc nhiều data center vật lý riêng biệt trong một Region. Mỗi AZ có nguồn điện, mạng, và kết nối độc lập. Dùng multi-AZ để tăng tính sẵn sàng (high availability).",
    category: "Core",
    relatedTerms: ["region"],
  },
  {
    id: "iam",
    term: "IAM (Identity and Access Management)",
    definition: "Dịch vụ quản lý danh tính và quyền truy cập AWS. Cho phép bạn tạo Users, Groups, Roles, và Policies để kiểm soát ai có thể làm gì trong tài khoản AWS của bạn.",
    category: "Security",
    relatedTerms: ["iam-policy", "iam-role", "least-privilege"],
  },
  {
    id: "iam-policy",
    term: "IAM Policy",
    definition: "Tài liệu JSON định nghĩa quyền truy cập (permissions). Mỗi policy chứa các Statement với Effect (Allow/Deny), Action (hành động được phép/từ chối), và Resource (tài nguyên áp dụng).",
    category: "Security",
    relatedTerms: ["iam", "iam-role"],
  },
  {
    id: "iam-role",
    term: "IAM Role",
    definition: "Danh tính AWS có thể được assume bởi service, user, hoặc tài khoản khác. Không có username/password, thay vào đó dùng temporary credentials. EC2, Lambda, ECS cần Role để truy cập AWS resources.",
    category: "Security",
    relatedTerms: ["iam", "iam-policy"],
  },
  {
    id: "least-privilege",
    term: "Least Privilege (Quyền tối thiểu)",
    definition: "Nguyên tắc bảo mật: chỉ cấp quyền tối thiểu cần thiết để thực hiện công việc. Không bao giờ cấp admin cho service nếu nó chỉ cần đọc S3.",
    category: "Security",
    relatedTerms: ["iam", "iam-policy"],
  },
  {
    id: "s3",
    term: "S3 (Simple Storage Service)",
    definition: "Dịch vụ lưu trữ object của AWS. Lưu trữ bất kỳ loại file nào (images, videos, backups, code). Không có giới hạn dung lượng, 99.999999999% độ bền dữ liệu.",
    category: "Storage",
    relatedTerms: ["s3-bucket", "s3-object", "pre-signed-url"],
  },
  {
    id: "s3-bucket",
    term: "S3 Bucket",
    definition: "Container chứa objects trong S3. Tên bucket phải unique toàn cầu. Mỗi bucket thuộc một Region cụ thể và có thể cấu hình versioning, lifecycle, và access control.",
    category: "Storage",
    relatedTerms: ["s3", "s3-object"],
  },
  {
    id: "s3-object",
    term: "S3 Object",
    definition: "File được lưu trong S3 Bucket. Mỗi object có key (tên file), value (nội dung), metadata, và version ID (nếu bật versioning). Kích thước tối đa 5TB.",
    category: "Storage",
    relatedTerms: ["s3", "s3-bucket"],
  },
  {
    id: "pre-signed-url",
    term: "Pre-signed URL",
    definition: "URL tạm thời cho phép truy cập S3 object mà không cần AWS credentials. Dùng để cho phép user upload/download file trực tiếp từ/lên S3 qua browser. Có thời hạn hết hạn cấu hình được.",
    category: "Storage",
    relatedTerms: ["s3", "s3-object"],
  },
  {
    id: "ec2",
    term: "EC2 (Elastic Compute Cloud)",
    definition: "Dịch vụ máy chủ ảo của AWS. Cho phép chạy bất kỳ ứng dụng nào trên server Linux hoặc Windows. Có hàng trăm loại instance với cấu hình CPU, RAM, GPU khác nhau.",
    category: "Compute",
    relatedTerms: ["ami", "security-group", "key-pair", "ebs"],
  },
  {
    id: "ami",
    term: "AMI (Amazon Machine Image)",
    definition: "Template để tạo EC2 instance, bao gồm OS, cài đặt phần mềm, và cấu hình. Có thể dùng AMI công khai của AWS (Ubuntu, Amazon Linux, Windows) hoặc tạo AMI riêng từ instance đã cấu hình.",
    category: "Compute",
    relatedTerms: ["ec2"],
  },
  {
    id: "security-group",
    term: "Security Group",
    definition: "Firewall ảo cho EC2 instance. Kiểm soát traffic vào (inbound) và ra (outbound). Theo mặc định chặn tất cả inbound và cho phép tất cả outbound. Security group là stateful.",
    category: "Networking",
    relatedTerms: ["ec2", "vpc", "nacl"],
  },
  {
    id: "vpc",
    term: "VPC (Virtual Private Cloud)",
    definition: "Mạng ảo riêng tư trong AWS, cô lập logic với các mạng khác. Bạn có toàn quyền kiểm soát IP address range, subnets, route tables, và network gateways.",
    category: "Networking",
    relatedTerms: ["subnet", "internet-gateway", "nat-gateway"],
  },
  {
    id: "subnet",
    term: "Subnet",
    definition: "Phân đoạn mạng con trong VPC. Public subnet có route đến Internet Gateway (instances có public IP). Private subnet không có route trực tiếp ra Internet, dùng NAT Gateway để ra ngoài.",
    category: "Networking",
    relatedTerms: ["vpc", "internet-gateway", "nat-gateway"],
  },
  {
    id: "internet-gateway",
    term: "Internet Gateway (IGW)",
    definition: "Cổng kết nối VPC với Internet. Instances trong public subnet cần IGW để giao tiếp với Internet. Mỗi VPC chỉ có một IGW.",
    category: "Networking",
    relatedTerms: ["vpc", "subnet"],
  },
  {
    id: "nat-gateway",
    term: "NAT Gateway",
    definition: "Cho phép instances trong private subnet kết nối ra Internet (download packages, gọi API bên ngoài) mà không expose IP của chúng. Tốn phí hourly và theo data transfer.",
    category: "Networking",
    relatedTerms: ["vpc", "subnet"],
  },
  {
    id: "rds",
    term: "RDS (Relational Database Service)",
    definition: "Dịch vụ database quan hệ được quản lý bởi AWS. Hỗ trợ PostgreSQL, MySQL, MariaDB, Oracle, SQL Server, Aurora. AWS lo backups, patching, và failover tự động.",
    category: "Database",
    relatedTerms: ["multi-az", "read-replica"],
  },
  {
    id: "dynamodb",
    term: "DynamoDB",
    definition: "Database NoSQL fully managed, serverless. Hiệu năng cực cao (<10ms latency), tự động scale. Dùng cho dữ liệu không cấu trúc hoặc cần read/write tốc độ cao.",
    category: "Database",
    relatedTerms: ["partition-key", "sort-key", "gsi"],
  },
  {
    id: "lambda",
    term: "Lambda",
    definition: "Dịch vụ compute serverless. Chạy code mà không cần quản lý server. Chỉ trả tiền khi code chạy (tính theo invocations và duration). Hỗ trợ Node.js, Python, Java, Go, .NET, Ruby.",
    category: "Compute",
    relatedTerms: ["api-gateway", "cold-start"],
  },
  {
    id: "api-gateway",
    term: "API Gateway",
    definition: "Dịch vụ tạo và quản lý RESTful và WebSocket APIs. Thường kết hợp với Lambda để tạo serverless backends. Hỗ trợ authentication, rate limiting, caching.",
    category: "Networking",
    relatedTerms: ["lambda"],
  },
  {
    id: "cold-start",
    term: "Cold Start",
    definition: "Độ trễ khởi động lần đầu của Lambda function khi không có instance nào đang chạy. Thường từ 100ms đến 1s tùy runtime. Có thể giảm bằng Provisioned Concurrency.",
    category: "Compute",
    relatedTerms: ["lambda"],
  },
  {
    id: "cloudwatch",
    term: "CloudWatch",
    definition: "Dịch vụ monitoring và observability của AWS. Thu thập logs, metrics, và events từ tất cả AWS services. Có thể tạo alarms để thông báo khi có vấn đề (CPU cao, error rate tăng).",
    category: "Monitoring",
    relatedTerms: ["cloudtrail"],
  },
  {
    id: "cloudfront",
    term: "CloudFront",
    definition: "Content Delivery Network (CDN) của AWS. Phân phối nội dung từ edge locations gần người dùng nhất, giảm latency và tăng tốc độ tải. Thường dùng với S3 để serve static files.",
    category: "Networking",
    relatedTerms: ["s3", "oac"],
  },
  {
    id: "alb",
    term: "ALB (Application Load Balancer)",
    definition: "Load balancer hoạt động ở Layer 7 (HTTP/HTTPS). Phân phối traffic đến nhiều instances/containers. Hỗ trợ path-based routing, host-based routing, và sticky sessions.",
    category: "Networking",
    relatedTerms: ["ec2", "ecs", "target-group"],
  },
  {
    id: "ecs",
    term: "ECS (Elastic Container Service)",
    definition: "Dịch vụ chạy container (Docker) của AWS. Không cần quản lý cluster. Có thể dùng EC2 instances hoặc Fargate (serverless). Tích hợp tốt với ALB, IAM, CloudWatch.",
    category: "Compute",
    relatedTerms: ["fargate", "ecr", "alb"],
  },
  {
    id: "fargate",
    term: "Fargate",
    definition: "Mode serverless cho ECS và EKS. Không cần quản lý EC2 instances, AWS tự lo phần cơ sở hạ tầng. Chỉ cần chỉ định CPU và RAM cho container. Trả tiền theo resource sử dụng.",
    category: "Compute",
    relatedTerms: ["ecs"],
  },
  {
    id: "sqs",
    term: "SQS (Simple Queue Service)",
    definition: "Dịch vụ hàng đợi tin nhắn fully managed. Decouples các thành phần của ứng dụng. Hỗ trợ Standard Queue (at-least-once delivery) và FIFO Queue (exactly-once, in-order).",
    category: "Messaging",
    relatedTerms: ["sns", "lambda", "dlq"],
  },
  {
    id: "dlq",
    term: "Dead Letter Queue (DLQ)",
    definition: "Hàng đợi nhận các messages không thể xử lý được sau nhiều lần thử. Dùng để debug và không mất dữ liệu khi có lỗi. Áp dụng được cho cả SQS và SNS.",
    category: "Messaging",
    relatedTerms: ["sqs"],
  },
  {
    id: "secrets-manager",
    term: "Secrets Manager",
    definition: "Dịch vụ lưu trữ và rotate secrets (database passwords, API keys). Ứng dụng đọc secret tại runtime thay vì hardcode. Hỗ trợ automatic rotation cho RDS passwords.",
    category: "Security",
    relatedTerms: ["kms", "parameter-store"],
  },
  {
    id: "kms",
    term: "KMS (Key Management Service)",
    definition: "Dịch vụ quản lý encryption keys. Tạo và kiểm soát cryptographic keys dùng để mã hóa dữ liệu. Tích hợp với hầu hết AWS services (S3, RDS, Secrets Manager).",
    category: "Security",
    relatedTerms: ["secrets-manager"],
  },
  {
    id: "terraform",
    term: "Terraform",
    definition: "Công cụ Infrastructure as Code open-source của HashiCorp. Dùng ngôn ngữ HCL để định nghĩa infrastructure. Hỗ trợ nhiều cloud providers (AWS, GCP, Azure). Quản lý state trong file terraform.tfstate.",
    category: "IaC",
    relatedTerms: ["cloudformation", "cdk"],
  },
  {
    id: "free-tier",
    term: "AWS Free Tier",
    definition: "Bậc miễn phí AWS dành cho tài khoản mới. Bao gồm Always Free (t2.micro EC2, 5GB S3...), 12 Months Free, và dùng thử có thời hạn. CẢNH BÁO: Không phải tất cả đều miễn phí, cần theo dõi billing cẩn thận.",
    category: "Core",
  },
];
