import type { Resource } from "@/types/guide";

export const resources: Resource[] = [
  {
    id: "aws-docs",
    title: "AWS Documentation",
    description: "Tài liệu chính thức của AWS. Đây là nguồn tài liệu đầy đủ và chính xác nhất cho mọi dịch vụ AWS.",
    url: "https://docs.aws.amazon.com",
    type: "official",
    tags: ["documentation", "reference"],
    isFree: true,
  },
  {
    id: "aws-training",
    title: "AWS Training & Certification",
    description: "Khóa học chính thức từ AWS, bao gồm các khóa học miễn phí và có phí. Chuẩn bị cho các chứng chỉ AWS.",
    url: "https://aws.amazon.com/training",
    type: "course",
    tags: ["training", "certification"],
    isFree: false,
  },
  {
    id: "aws-skill-builder",
    title: "AWS Skill Builder",
    description: "Nền tảng học trực tuyến của AWS với hàng trăm khóa học miễn phí và có phí. Bao gồm labs thực hành.",
    url: "https://skillbuilder.aws",
    type: "course",
    tags: ["training", "labs", "free"],
    isFree: false,
  },
  {
    id: "aws-well-architected",
    title: "AWS Well-Architected Framework",
    description: "Framework thiết kế kiến trúc tốt trên AWS với 6 pillars: Operational Excellence, Security, Reliability, Performance, Cost, Sustainability.",
    url: "https://aws.amazon.com/architecture/well-architected",
    type: "official",
    tags: ["architecture", "best-practices"],
    isFree: true,
  },
  {
    id: "aws-architecture-center",
    title: "AWS Architecture Center",
    description: "Thư viện kiến trúc tham khảo, patterns, và whitepapers cho các use cases phổ biến trên AWS.",
    url: "https://aws.amazon.com/architecture",
    type: "official",
    tags: ["architecture", "diagrams"],
    isFree: true,
  },
  {
    id: "aws-youtube",
    title: "AWS YouTube Channel",
    description: "Kênh YouTube chính thức của AWS với hàng nghìn video về dịch vụ, re:Invent talks, và tutorials.",
    url: "https://www.youtube.com/@amazonwebservices",
    type: "video",
    tags: ["video", "tutorials"],
    isFree: true,
  },
  {
    id: "cloudguru",
    title: "A Cloud Guru",
    description: "Nền tảng học AWS nổi tiếng với video courses, hands-on labs, và practice exams cho chứng chỉ AWS.",
    url: "https://acloudguru.com",
    type: "course",
    tags: ["course", "certification"],
    isFree: false,
  },
  {
    id: "stephane-maarek",
    title: "Udemy - Stephane Maarek AWS Courses",
    description: "Các khóa học AWS nổi tiếng nhất trên Udemy bởi Stephane Maarek. Rất thực tế, đầy đủ, và liên tục cập nhật.",
    url: "https://www.udemy.com/user/stephane-maarek",
    type: "course",
    tags: ["course", "certification", "video"],
    isFree: false,
  },
  {
    id: "aws-calculator",
    title: "AWS Pricing Calculator",
    description: "Tính toán chi phí ước tính cho infrastructure AWS của bạn trước khi triển khai.",
    url: "https://calculator.aws/pricing/2/home",
    type: "tool",
    tags: ["pricing", "cost"],
    isFree: true,
  },
  {
    id: "aws-free-tier-tracker",
    title: "AWS Free Tier Usage Alerts",
    description: "Hướng dẫn cài đặt billing alerts để tránh bị tính phí ngoài ý muốn khi học AWS Free Tier.",
    url: "https://docs.aws.amazon.com/awsaccountbilling/latest/aboutv2/tracking-free-tier-usage.html",
    type: "official",
    tags: ["billing", "free-tier"],
    isFree: true,
  },
  {
    id: "aws-cli-docs",
    title: "AWS CLI Documentation",
    description: "Tài liệu chính thức AWS CLI với tất cả commands và options cho mọi dịch vụ.",
    url: "https://docs.aws.amazon.com/cli/latest/reference",
    type: "official",
    tags: ["cli", "reference"],
    isFree: true,
  },
  {
    id: "aws-cdk-docs",
    title: "AWS CDK Documentation",
    description: "Tài liệu chính thức AWS Cloud Development Kit (CDK) - Infrastructure as Code bằng TypeScript/Python.",
    url: "https://docs.aws.amazon.com/cdk/v2/guide/home.html",
    type: "official",
    tags: ["iac", "cdk"],
    isFree: true,
  },
];
